const mongoose=require("mongoose")
const StudentSchema=new mongoose.Schema(
    {
        name:{
            type:String,
            required:true
        },
        email:{
            type:String,
            required:true
        },
        phone:{
            type:Number,
            required:true
        },
        dob:{
            type:String

        },
        gender:{
            type:String
        },
        address:{
            type:String
        },
        qualification:{
            type:String
        },
        guardianName:{
            type:String
        },
        guardianPhone:{
            type:Number
        },
        course:{
            type:String,
            required:true
        },
        batch:{
            type:String
        },
        joiningdate:{
            type:String,
            required:true
        },
        fees:{
            type:Number
        },
        trainer:{
            type:String,
            required:true
        },
        trainerid:{
            type:Number
        },
        status:{
            type:String,
            required:true
        }
    }
)
module.exports=mongoose.model("Student",StudentSchema)